<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheels">

    <xacro:macro name="wheel_visual" params="wheel_radius">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${track_width}" radius="${wheel_radius+track_thickness}" />
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1" />
            </material>
        </visual>
    </xacro:macro>

    <xacro:macro name="sprocket_wheel_visual">
        <xacro:wheel_visual wheel_radius="${sprocket_wheel_radius}" />
    </xacro:macro>

    <xacro:macro name="idler_wheel_visual">
        <xacro:wheel_visual wheel_radius="${idler_wheel_radius}" />
    </xacro:macro>

    <xacro:macro name="left_sprocket_wheel_visual">
        <xacro:sprocket_wheel_visual />
    </xacro:macro>

    <xacro:macro name="right_sprocket_wheel_visual">
        <xacro:sprocket_wheel_visual />
    </xacro:macro>

    <xacro:macro name="left_idler_wheel_visual">
        <xacro:sprocket_wheel_visual />
    </xacro:macro>

    <xacro:macro name="right_idler_wheel_visual">
        <xacro:sprocket_wheel_visual />
    </xacro:macro>

</robot>