# kinematic: skid_steering
type: 2THD
geometry:
  # tracks_distance: 1.137
  tracks_distance: 0.91  # mesured on the INRAE robot
  tracks:
    width: 0.18
    thickness: 0.03
    sprocket_wheel:
      radius: 0.144
      mass: 1.0
      x: -0.32
      z: 0.4
    front_idler_wheel:
      radius: 0.103
      mass: 0.5
      x: 0.45
      z: 0.103
    rear_idler_wheel:
      radius: 0.103
      mass: 0.5
      x: -0.42
      z: 0.103
    roller_wheels:
      radius: 0.0675
      mass: 0.5
      x: [-0.14, 0.14]
      z: 0.0675
  aabb:
    length: 2.3490
    width: 0.7000
    height: 1.1330
    center: [0., 0., 0.68]
  ground_clearance: 0.21

tracks_speed_control:
  command:
    maximal_speed: 2.0
    maximal_acceleration: 1.0
  sensor:
    speed_std: 0.1
    speed_range: 2.0

inertia:
  mass: 340.
  center: [0., 0., 0.71650]
  z_moment: 239.

control_point : [0.0, 0.0, 0.0]

joints:
  base_footprint_joint_name : base_footprint
  inertial_joint_name: inertial_joint
  left_sprocket_wheel_spinning_joint_name: left_sprocket_wheel_spinning_joint
  right_sprocket_wheel_spinning_joint_name: right_sprocket_wheel_spinning_joint
  front_left_idler_wheel_spinning_joint_name: front_left_idler_wheel_spinning_joint
  front_right_idler_wheel_spinning_joint_name: front_left_idler_right_spinning_joint
  rear_left_idler_wheel_spinning_joint_name: rear_left_idler_wheel_spinning_joint
  rear_right_idler_wheel_spinning_joint_name: rear_left_idler_right_spinning_joint
  
links:
  base_link_name: base_link
  base_footprint_link_name: base_footprint
  inertial_link_name: inertial_link
  left_sprocket_wheel_spinning_link_name: left_sprocket_wheel_spinning_link
  right_sprocket_wheel_spinning_link_name: right_sprocket_wheel_spinning_link
  front_left_idler_wheel_spinning_link_name: front_left_idler_wheel_spinning_link
  front_right_idler_wheel_spinning_link_name: front_left_idler_right_spinning_link
  rear_left_idler_wheel_spinning_link_name: rear_left_idler_wheel_spinning_link
  rear_right_idler_wheel_spinning_link_name: rear_left_idler_right_spinning_link

